<a href="https://colab.research.google.com/github/aviaga/FutureMakers/blob/main/Day%2021%20(7-26)%20-%20Project%201%20on%20Adding%20Upsampling%20Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Intro

This is the implementation of Day 21's first Action Item for SureStart's summer program, 2021.

The goal of the project is to explore Upsampling in Deep Learning models. 

The tutorial for this model development activity can be found [here](https://machinelearningmastery.com/upsampling-and-transpose-convolution-layers-for-generative-adversarial-networks/).

**Worked Example Using the UpSampling 2D Layer**

In [1]:
#Import libraries
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

In [2]:
#Defining and showing input data
X = asarray([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [3]:
#Reshaping data to work with dataset
X = X.reshape((1, 2, 2, 1))

In [4]:
#Defining model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))

In [5]:
#Outputs: Summarzing the model, making a prediction, reshaping for visual purposes, and summarizing the output
model.summary()
yhat = model.predict(X)
yhat = yhat.reshape((4, 4))
print(yhat)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d (UpSampling2D) (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


**Generator Model with UpSampling2D Layer**

In [6]:
#Import libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D

In [7]:
#Defining model architecture, reshaping data, adding UpSampling
model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
model.add(Reshape((5, 5, 128)))
model.add(UpSampling2D())
model.add(Conv2D(1, (3,3), padding='same'))

In [8]:
#Output: Summarizing the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_1 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


**Worked Example Using Conv2DTranspose Layer**

In [9]:
#Import libraries
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

In [10]:
#Defining, showing, and reshaping input data
X = asarray([[1, 2],
			 [3, 4]])
print(X)
X = X.reshape((1, 2, 2, 1))

[[1 2]
 [3 4]]


In [11]:
#Defining the model and summarizing it
model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [12]:
#Defining and storing weights
weights = [asarray([[[[1]]]]), asarray([0])]
model.set_weights(weights)

In [13]:
#Outputs: Making a prediction, reshaping for visual purposes, summarizing output
yhat = model.predict(X)
yhat = yhat.reshape((4, 4))
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


**Generator Model with Conv2DTranspose Layer**

In [14]:
#Import libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Conv2DTranspose
from keras.layers import Conv2D

In [15]:
#Defining model architecture
model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))

In [16]:
#Reshaping data and doubling input
model.add(Reshape((5, 5, 128)))
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))

In [17]:
#Output: Summarizing the model
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
